### ISSUE TITLE
Only "chameleonizes" once per session

### ISSUE THREAD

**Issue by marcioAlmada** [r3a1ay/flat-chameleon-sublime-theme#2]
Hi, I love your plugin but I can only chameleonize once per session. Steps:

0. Open sublime
0. Change color scheme
0. Run "Flat Chameleon: chameleonize" command through command palette
0. Theme changes :+1: 
0. Change color scheme again
0. Run "Flat Chameleon: chameleonize" command through command palette
0. Theme doesn't change anymore :sob:
0. Close sublime & back to step 1

I have to close and reopen sublime to try a new color.

**Comment by r3a1ay** [comment]
Hi, what you have in sublime's console after step 6?

**Comment by marcioAlmada** [comment]
reloading Packages/User/Widget.sublime-settings
    warning: mnemonic g not found in menu caption Git GUI Clients

**Comment by r3a1ay** [comment]
Thanks.
Fixed in v1.2.8.

**Comment by marcioAlmada** [comment]
So quick - works as expected now. Thanks!
